version: '3.5'
services:
  slave1:
    container_name: c1
    image: mall/consumer:1.0.0
    networks:
      - mall-server-net
    ports:
      - 6761:6761
    environment:
      - SPRING_PROFILES_ACTIVE=slave1


networks:
  mall-server-net:
    name: mall-server-net
    driver: bridge