#参考：https://my.oschina.net/AmosWang/blog/2990803
spring:
  application:
    name: eureka-server
management:
  security:
    enabled: false
security:
  basic:
    enabled: true
  user:
    password: dx
    name: dx

--- #注意这里是三个"减号"
spring:
  profiles: eureka6001     # 指定profile=Eureka6001
server:
  port: 6001
eureka:
  instance:
    hostname: eureka6001        # 指定当profile=6001时，主机名是localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://dx:dx@eureka6002:6002/eureka/,http://dx:dx@eureka6003:6003/eureka/      # 将自己注册到6002,6003的Eureka上面去

--- #注意这里是三个"减号"
spring:
  profiles: eureka6002     # 指定profile=Eureka6002
server:
  port: 6002
eureka:
  instance:
    hostname: eureka6002        # 指定当profile=6001时，主机名是localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://dx:dx@eureka6001:6001/eureka/,http://dx:dx@eureka6003:6003/eureka/      # 将自己注册到6001,6003的Eureka上面去

--- #注意这里是三个"减号"
spring:
  profiles: eureka6003     # 指定profile=Eureka6002
server:
  port: 6002
eureka:
  instance:
    hostname: eureka6003        # 指定当profile=6001时，主机名是localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://dx:dx@eureka6001:6001/eureka/,http://dx:dx@eureka6002:6002/eureka/      # 将自己注册到6001,6002的Eureka上面去
 